server:
  port: 9999


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

zuul:
  ignoredServices: '*'
  routes:
      product-service:
        path: /products/**
        stripPrefix: false
      loanservice:
        path: /loan/**
        stripPrefix: false





management:
  endpoints:
    web:
      exposure:
          include: routes,filters

