server:
  port: 9999


zuul:
  host:
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000

  ratelimit:
    enabled: true
    behind-proxy: true
    add-response-headers: true
    default-policy-list:
      - limit: 10
        refresh-interval: 60
        quota: 10

  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    userservice:
      path: /user/**
#      url: http://192.168.110.5:8089/api/user
      url: ec2-3-0-177-136.ap-southeast-1.compute.amazonaws.com:8089/api/user
    examservice:
      path: /exam/**
      url: http://192.168.109.95:8085/api/exam
    authservice:
      path: /auth/**
      url: http://192.168.109.190:8083/api/auth
    kpiservice:
      path: /kpi/**
      url: http://192.168.108.107:8081/api/kpi

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


spring:
  application:
    name: zuul-service
  authService:
    host: http://192.168.109.190:8083/api/auth
    endpoint:
      getVerify: verify

management:
  endpoints:
    web:
      exposure:
        include: routes,filters