server:
  port: 9999


zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    customerservice:
      path: /api/customer/**
      stripPrefix: false
      url: http://localhost:8081
    loanservice:
      path: /api/loan/**
      stripPrefix: false
      url: http://localhost:8082
    mockservice:
      path: /mock/**
      url: http://localhost:9000/


spring:
  application:
    name: zuul-service

management:
  endpoints:
    web:
      exposure:
        include: routes,filters