server:
  port: 9999


zuul:
  host:
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000

#    LIMIT REQUEST 1TIME/SEC
  ratelimit:
    enabled: true
    behind-proxy: true
    add-response-headers: true
    default-policy-list:       #optional - will apply unless specific policy exists
      - limit: 1               #optional - request number limit per refresh interval window
        refresh-interval: 2    #default value (in seconds)
        quota: 10              #optional - request time limit per refresh interval window (in seconds)
#         /////////////

  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    customerservice:
#      example
      path: /customer/**
      url: http://localhost:8081/api/customer
    loanservice:
      path: /api/loan/**
      url: http://localhost:8082/api/loan
#        /////
    userservice:
      path: /user/**
      url: http://192.168.109.211:8089/api/user
    examservice:
      path: /exam/**
      url: http://192.168.109.167:8085/api/exam
    authservice:
      path: /auth/**
      url: http://192.168.109.204:8083/api/auth
    kpiservice:
      path: /kpi/**
      url: http://localhost:8081/api/kpi
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


spring:
  application:
    name: zuul-service

management:
  endpoints:
    web:
      exposure:
        include: routes,filters