server:
  port: 9999


zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    hello:
      path: /hello/**
      stripPrefix: false
      url: http://localhost:8899
    loan-service:
      path: /api/loan/**
      stripPrefix: false
      url: http://localhost:8082


spring:
  application:
    name: zuul-service

management:
  endpoints:
    web:
      exposure:
        include: routes,filters