server:
  port: 9999


zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    customerservice:
      path: /api/customer/**
      stripPrefix: false
      url: http://localhost:8081
    loanservice:
      path: /api/loan/**
      stripPrefix: false
      url: http://localhost:8082
    hello:
      path: /hello/**
      stripPrefix: false
      serviceId: test
    userservice:
      path: /api/user/**
      stripPrefix: false
      url: http://13.251.220.186:8081
    mockservice:
      path: /mock/**
      url: http://localhost:9000/

test:
  ribbon:
    listOfServers: http://localhost:8899

spring:
  application:
    name: zuul-service

management:
  endpoints:
    web:
      exposure:
        include: routes,filters