server:
  port: 9999


zuul:
  host:
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
    semaphore:
      max-semaphores: 500

  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    customerservice:
#      example
      path: /api/customer/**
      stripPrefix: false
      url: http://localhost:8081
    loanservice:
      path: /api/loan/**
      stripPrefix: false
      url: http://localhost:8082
#        /////
    userservice:
      path: /user/**
      url: http://192.168.109.211:8089/api/user
    examservice:
      path: /exam/**
      url: http://192.168.109.167:8085/api/exam
    authservice:
      path: /auth/**
      url: http://192.168.109.204:8083/api/auth
    kpiservice:
      path: /kpi/**
      url: http://localhost:8081/api/kpi
ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

#ratelimit:
#  enabled: true
#  policy-list:
#    loanservice:
#      - limit: 5
#        refresh-interval: 60
#        type:
#          - origin
#    customerservice:
#      - limit: 1
#        refresh-interval: 2
#        type:
#          - origin

spring:
  application:
    name: zuul-service

management:
  endpoints:
    web:
      exposure:
        include: routes,filters