server:
  port: 9999


zuul:
  host:
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000

#    LIMIT REQUEST 1TIME/SEC
  ratelimit:
    enabled: true
    behind-proxy: true
    add-response-headers: true
    default-policy-list:       #optional - will apply unless specific policy exists
      - limit: 10               #optional - request number limit per refresh interval window
        refresh-interval: 60    #default value (in seconds)
        quota: 10              #optional - request time limit per refresh interval window (in seconds)
#         /////////////

  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    customerservice:
#      example
      path: /customer/**
      url: http://localhost:8081/api/customer
    loanservice:
      path: /api/loan/**
      url: http://localhost:8082/api/loan
#        /////
    userservice:
      path: /user/**
      url: http://192.168.110.5:8089/api/user
#      url: http://localhost:1001/api/user
    examservice:
      path: /exam/**
      url: http://192.168.109.95:8085/api/exam
    authservice:
      path: /auth/**
      url: http://192.168.109.190:8083/api/auth
    kpiservice:
      path: /kpi/**
      url: http://192.168.111.189:8081/api/kpi

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


spring:
  application:
    name: zuul-service
  authService:
#    host: http://192.168.43.114:8083/api/auth
    host: http://192.168.109.190:8083/api/auth
#    host: http://localhost:9977/api/auth
    endpoint:
      getVerify: verify

management:
  endpoints:
    web:
      exposure:
        include: routes,filters